# Generated by Django 6.0.1 on 2026-02-10 20:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_category', models.CharField(choices=[('Email Account', 'Email Account'), ('Social Media Account', 'Social Media Account'), ('Cloud Storage Account', 'Cloud Storage Account'), ('Streaming Media Account', 'Streaming Media Account'), ('Ecommerce Marketplace Account', 'Ecommerce Marketplace Account'), ('Online Banking Account', 'Online Banking Account'), ('Neobank/Digital Bank Account', 'Neobank/Digital Bank Account'), ('Brokerage/Investment Account', 'Brokerage/Investment Account'), ('Cryptocurrency Exchange Account', 'Cryptocurrency Exchange Account'), ('Payment Wallet Account', 'Payment Wallet Account'), ('Payment Processor Account', 'Payment Processor Account'), ('App Store Account', 'App Store Account'), ('Gaming Platform Account', 'Gaming Platform Account'), ('Forum/Community Account', 'Forum/Community Account'), ('Education/Elearning Account', 'Education/Elearning Account'), ('Subscription Account', 'Subscription Account'), ('Government Portal Account', 'Government Portal Account'), ('Utilities/Telecom Portal Account', 'Utilities/Telecom Portal Account'), ('Health Portal Account', 'Health Portal Account'), ('Smart Home/IoT Account', 'Smart Home/IoT Account'), ('Travel Booking Account', 'Travel Booking Account'), ('Password Manager Account', 'Password Manager Account'), ('Not Listed', 'Not Listed')], default='email', max_length=200)),
                ('account_name_or_provider', models.CharField(help_text='Account name or service', max_length=200)),
                ('website_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('username_or_email', models.CharField(blank=True, help_text='Username or email used for login', max_length=200)),
                ('credential_storage_location', models.CharField(blank=True, help_text='Where password is stored (e.g., 1Password, LastPass)', max_length=500)),
                ('is_critical', models.BooleanField(default=False, help_text='Mark as critical/important account')),
                ('keep_or_close_instruction', models.CharField(choices=[('Keep Active', 'Keep Active'), ('Close Account', 'Close Account'), ('Memorialize', 'Memorialize'), ('Other (See Notes)', 'Other (See Notes)')], default='other', max_length=20)),
                ('notes_for_family', models.TextField(blank=True, help_text='Instructions or notes for family members')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts',
                'ordering': ['-is_critical', 'account_name_or_provider'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(default='Enter name', max_length=200)),
                ('body', models.TextField(help_text='Emergency message content')),
                ('contact_relation', models.CharField(choices=[('Spouse', 'Spouse'), ('Mother', 'Mother'), ('Father', 'Father'), ('Sister', 'Sister'), ('Brother', 'Brother'), ('Daughter', 'Daughter'), ('Son', 'Son'), ('Mother-in-law', 'Mother-in-law'), ('Father-in-law', 'Father-in-law'), ('Sister-in-law', 'Sister-in-law'), ('Brother-in-law', 'Brother-in-law'), ('Daughter-in-law', 'Daughter-in-law'), ('Son-in-Law', 'Son-in-Law'), ('Cousin', 'Cousin'), ('Other', 'Other')], max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('is_emergency_contact', models.BooleanField(default=False)),
                ('is_digital_executor', models.BooleanField(default=False)),
                ('is_caregiver', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'primary_contacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountRelevanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matters', models.BooleanField(default=True, help_text='Does this account still matter?')),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('reasoning', models.TextField(blank=True)),
                ('next_review_due', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relevance_reviews', to='dashboard.account')),
                ('reviewer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='account_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_relevance_reviews',
                'ordering': ['-review_date'],
            },
        ),
        migrations.CreateModel(
            name='FamilyNeedsToKnowSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='What family needs to know')),
                ('is_location_of_legal_will', models.BooleanField(default=False)),
                ('is_password_manager', models.BooleanField(default=False)),
                ('is_social_media', models.BooleanField(default=False)),
                ('is_photos_or_files', models.BooleanField(default=False)),
                ('is_data_retention_preferences', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_relations', to='dashboard.contact')),
            ],
            options={
                'db_table': 'family_needs_to_know_sections',
                'ordering': ['relation', 'content'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('primary_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Personal notes')),
                ('has_digital_executor', models.BooleanField(default=False, help_text='Have you designated a digital executor?')),
                ('digital_executor_name', models.CharField(blank=True, max_length=200)),
                ('digital_executor_contact', models.CharField(blank=True, help_text='Email or phone number', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('Phone', 'Phone'), ('Tablet', 'Tablet'), ('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Smart Watch', 'Smart Watch'), ('Other', 'Other')], max_length=20)),
                ('name', models.CharField(help_text='Device name or model', max_length=200)),
                ('owner_label', models.CharField(blank=True, help_text="e.g., 'Mom's iPhone', 'Work Laptop'", max_length=100)),
                ('location_description', models.CharField(blank=True, help_text='Where device is typically kept', max_length=200)),
                ('unlock_method_description', models.CharField(blank=True, help_text='How to unlock (without revealing actual password)', max_length=200)),
                ('used_for_2fa', models.BooleanField(default=False)),
                ('decommission_instruction', models.TextField(blank=True, help_text='What to do with this device after death')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='dashboard.profile')),
            ],
            options={
                'db_table': 'devices',
                'ordering': ['device_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='profile',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='relation_contacts', to='dashboard.profile'),
        ),
        migrations.CreateModel(
            name='Checkup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi-annual', 'Semi-Annual'), ('annual', 'Annual')], max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('all_accounts_reviewed', models.BooleanField(default=False)),
                ('all_devices_reviewed', models.BooleanField(default=False)),
                ('contacts_up_to_date', models.BooleanField(default=False)),
                ('documents_up_to_date', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_checkups', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='checkups', to='dashboard.profile')),
            ],
            options={
                'db_table': 'checkups',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='CareRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('Caregiver', 'Caregiver'), ('Healthcare-proxy', 'Healthcare Proxy'), ('Power-of-attorney', 'Power of Attorney'), ('Trustee', 'Trustee'), ('Other', 'Other')], max_length=30)),
                ('has_portal_access', models.BooleanField(default=False, help_text='Has access to digital estate portal')),
                ('portal_role', models.CharField(blank=True, choices=[('View Only', 'View Only'), ('Editor', 'Editor'), ('Administrator', 'Administrator')], default='view-only', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_relationships', to='dashboard.contact')),
                ('profile', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='care_relationships', to='dashboard.profile')),
            ],
            options={
                'db_table': 'care_relationships',
                'ordering': ['contact_name'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='profile',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='dashboard.profile'),
        ),
        migrations.CreateModel(
            name='RecoveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_description', models.CharField(help_text='Description of account to recover', max_length=500)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Denied', 'Denied'), ('Cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('provider_ticket_number', models.CharField(blank=True, max_length=100)),
                ('steps_taken', models.TextField(blank=True)),
                ('outcome_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='recovery_requests', to='dashboard.profile')),
                ('requested_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='recovery_requests_made', to=settings.AUTH_USER_MODEL)),
                ('target_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recovery_requests', to='dashboard.account')),
            ],
            options={
                'db_table': 'recovery_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_or_title', models.CharField(help_text='Specific name of Document', max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('document_category', models.CharField(choices=[('Personal Identification', "Driver's license, passport, and other official IDs."), ('Important Personal Documents', 'Birth certificate, marriage certificate, and similar records.'), ('Social Security Information', 'Social Security number and benefit details.'), ('Property Deeds and Titles', 'Ownership records for homes, vehicles, or land.'), ('Safe Deposit Box Information', 'Location, access instructions, and contents list.'), ('Medical Summary', 'Includes allergies, medications, medical history, and specialists.'), ('Care Preferences and Providers', 'In-home care, nursing home info, and care instructions.'), ('Health Insurance and Benefits', 'Insurance policy details, Medicare/Medicaid info.'), ('Dependents and Pet Care', 'Dependent care needs and pet care instructions.'), ('Funeral and Memorial Wishes', 'Funeral, burial, or memorial preferences.'), ('Bank and Cash Accounts', 'Checking, savings, and credit card details.'), ('Loans and Liabilities', 'Debts, mortgages, and other financial obligations.'), ('Investments and Retirement', 'Investment accounts, pensions, and annuities.'), ('Income and Budgets', 'Income sources, monthly bills, and recurring expenses.'), ('Insurance Policies', 'Life, disability, and long-term care policies.'), ('Tax and Financial Records', 'Tax returns, property records, and valuation documents.'), ('Business Ownership Documents', 'Operating agreements, partnership and ownership records.'), ('Charitable Giving and Memberships', 'Charitable plans, affiliations, and organizations.'), ('Online Accounts and Passwords', 'Online services, financial logins, and subscriptions.'), ('Cloud and Email Accounts', 'Cloud storage, email accounts, and access credentials.'), ('Password Management', 'Password manager info and recovery instructions.'), ('Social Media Accounts', 'Profiles and legacy social media preferences.'), ('Personal Property and Valuables', 'Inventory of personal valuables.'), ('Notes and Special Instructions', 'Additional notes or specific personal guidance.')], default='Important Personal Documents', max_length=50)),
                ('physical_location', models.CharField(blank=True, help_text='Where physical document is stored', max_length=200)),
                ('digital_location', models.CharField(blank=True, help_text='Where digital copy is stored', max_length=500)),
                ('important_file', models.FileField(blank=True, help_text='Upload digital copy', null=True, upload_to='documents/%Y/%m/')),
                ('requires_legal_review', models.BooleanField(default=False, help_text='Needs legal professional review')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delegated_to', models.ForeignKey(help_text='Contact who has access to this document', on_delete=django.db.models.deletion.PROTECT, related_name='delegated_important_documents', to='dashboard.contact')),
                ('profile', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='important_documents', to='dashboard.profile')),
            ],
            options={
                'db_table': 'important_documents',
                'ordering': ['delegated_to', 'document_category'],
                'indexes': [models.Index(fields=['profile', 'delegated_to'], name='important_d_profile_97ee93_idx')],
            },
        ),
        migrations.CreateModel(
            name='DigitalEstateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estate_document', models.CharField(choices=[('Healthcare Documents', [('Advance Directive / Living Will', 'Advance Directive / Living Will — States your wishes for end-of-life or critical medical care.'), ('Durable Power of Attorney for Healthcare', 'Durable Power of Attorney for Healthcare — Authorizes someone to make medical decisions if you cannot.'), ('Living Will / Advance Directive', 'Living Will / Advance Directive — States your wishes for end-of-life or critical medical care.'), ('HIPAA Authorizations', 'HIPAA Authorizations — Allows named individuals to access your medical information.'), ('Organ Donation Preferences', 'Organ Donation Preferences — Documents or forms stating your organ donation wishes.')]), ('Financial and Legal Documents', [('Durable Power of Attorney for Financial Matters', 'Durable Power of Attorney for Financial Matters — Authorizes someone to manage finances if you are incapacitated.'), ('Beneficiary Designations', 'Beneficiary Designations — Forms for life insurance, retirement accounts, etc., naming who receives benefits.'), ('Guardianship Designations', 'Guardianship Designations — Documents naming guardians for minor children or dependents.'), ('Trust Documents', 'Trust Documents — Revocable or irrevocable trust agreements holding and distributing property.')]), ('Estate Administration and Final Instructions', [('Executor / Personal Representative Info', 'Executor / Personal Representative Info — Information about the person(s) designated to administer your estate.'), ('Letter of Instruction', 'Letter of Instruction — Provides guidance for heirs, location of assets, and personal wishes.'), ('Will and Codicils', 'Will and Codicils — Last Will and Testament and any amendments (codicils).')])], default='important_personal_documents', max_length=200)),
                ('name_or_title', models.CharField(help_text='Specific name of Document', max_length=100)),
                ('estate_file', models.FileField(blank=True, help_text='Upload digital copy', null=True, upload_to='documents/%Y/%m/')),
                ('overall_instructions', models.CharField(blank=True, help_text='General instructions for family', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delegated_to', models.ForeignKey(help_text='Contact who has access to this document', on_delete=django.db.models.deletion.PROTECT, related_name='delegated_estate_documents', to='dashboard.contact')),
                ('profile', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='estate_documents', to='dashboard.profile')),
            ],
            options={
                'db_table': 'digital_estate_documents',
                'ordering': ['delegated_to', 'name_or_title', '-created_at'],
                'indexes': [models.Index(fields=['profile', 'delegated_to'], name='digital_est_profile_33790e_idx')],
            },
        ),
        migrations.CreateModel(
            name='DelegationGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delegation_category', models.CharField(choices=[('Estate and Property Oversight', 'Estate and Property Oversight'), ('Family Affairs', 'Family Affairs'), ('Financial Authority', 'Financial Authority'), ('Healthcare Decision-Making', 'Healthcare Decision-Making'), ('Personal Items', 'Personal Items')], default='Estate and Property Oversight', max_length=200)),
                ('applies_on_death', models.BooleanField(default=False)),
                ('applies_on_incapacity', models.BooleanField(default=False)),
                ('applies_immediately', models.BooleanField(default=False)),
                ('notes_for_contact', models.TextField(blank=True, help_text='Instructions for the contact')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delegate_to', models.ForeignKey(help_text='Contact receiving this delegation', on_delete=django.db.models.deletion.CASCADE, related_name='delegation_grants', to='dashboard.contact')),
                ('profile', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='delegation_grants', to='dashboard.profile')),
            ],
            options={
                'db_table': 'delegation_grants',
                'ordering': ['delegate_to', '-created_at'],
                'unique_together': {('profile', 'delegate_to')},
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['profile', '-created_at'], name='accounts_profile_bd7b53_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_category'], name='accounts_account_0ed7bc_idx'),
        ),
    ]
