# Generated by Django 6.0.1 on 2026-02-06 16:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(help_text='Account name or service', max_length=200)),
                ('account_category', models.CharField(choices=[('email', 'Email Account'), ('social_media', 'Social Media Account'), ('cloud_storage', 'Cloud Storage Account'), ('streaming_media', 'Streaming Media Account'), ('ecommerce_marketplace', 'Ecommerce Marketplace Account'), ('online_banking', 'Online Banking Account'), ('neobank_digital_bank', 'Neobank/Digital Bank Account'), ('brokerage_investment', 'Brokerage/Investment Account'), ('cryptocurrency_exchange', 'Cryptocurrency Exchange Account'), ('payment_wallet', 'Payment Wallet Account'), ('payment_processor', 'Payment Processor Account'), ('app_store', 'App Store Account'), ('gaming_platform', 'Gaming Platform Account'), ('forum_community', 'Forum/Community Account'), ('education_elearning', 'Education/Elearning Account'), ('subscription_saas', 'Subscription Account'), ('government_portal', 'Government Portal Account'), ('utilities_telecom_portal', 'Utilities/Telecom Portal Account'), ('health_portal', 'Health Portal Account'), ('smart_home_iot', 'Smart Home/IoT Account'), ('travel_booking', 'Travel Booking Account'), ('password_manager', 'Password Manager Account'), ('not_listed', 'Not Listed')], default='email', max_length=200)),
                ('provider', models.CharField(help_text='Company/service provider', max_length=200)),
                ('website_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('username_or_email', models.CharField(blank=True, help_text='Username or email used for login', max_length=200)),
                ('credential_storage_location', models.CharField(blank=True, help_text='Where password is stored (e.g., 1Password, LastPass)', max_length=500)),
                ('is_critical', models.BooleanField(default=False, help_text='Mark as critical/important account')),
                ('keep_or_close_instruction', models.CharField(choices=[('keep', 'Keep Active'), ('close', 'Close Account'), ('memorialize', 'Memorialize'), ('other', 'Other (See Notes)')], default='other', max_length=20)),
                ('notes_for_family', models.TextField(blank=True, help_text='Instructions or notes for family members')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts',
                'ordering': ['-is_critical', 'account_name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(default='Enter name', max_length=200)),
                ('body', models.TextField(help_text='Emergency message content')),
                ('contact_relation', models.CharField(choices=[('Spouse', 'Spouse'), ('Mother', 'Mother'), ('Father', 'Father'), ('Sister', 'Sister'), ('Brother', 'Brother'), ('Daughter', 'Daughter'), ('Son', 'Son'), ('Mother-in-law', 'Mother-in-law'), ('Father-in-law', 'Father-in-law'), ('Sister-in-law', 'Sister-in-law'), ('Brother-in-law', 'Brother-in-law'), ('Daughter-in-law', 'Daughter-in-law'), ('Son-in-Law', 'Son-in-Law'), ('Cousin', 'Cousin'), ('Other', 'Other')], max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('is_emergency_contact', models.BooleanField(default=False)),
                ('is_digital_executor', models.BooleanField(default=False)),
                ('is_caregiver', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'primary_contacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountRelevanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matters', models.BooleanField(default=True, help_text='Does this account still matter?')),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('reasoning', models.TextField(blank=True)),
                ('next_review_due', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relevance_reviews', to='dashboard.account')),
                ('reviewer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='account_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_relevance_reviews',
                'ordering': ['-review_date'],
            },
        ),
        migrations.CreateModel(
            name='FamilyNeedsToKnowSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='What family needs to know')),
                ('is_location_of_legal_will', models.BooleanField(default=False)),
                ('is_password_manager', models.BooleanField(default=False)),
                ('is_social_media', models.BooleanField(default=False)),
                ('is_photos_or_files', models.BooleanField(default=False)),
                ('is_data_retention_preferences', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_relations', to='dashboard.contact')),
            ],
            options={
                'db_table': 'family_needs_to_know_sections',
                'ordering': ['relation', 'content'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('primary_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Personal notes')),
                ('has_digital_executor', models.BooleanField(default=False, help_text='Have you designated a digital executor?')),
                ('digital_executor_name', models.CharField(blank=True, max_length=200)),
                ('digital_executor_contact', models.CharField(blank=True, help_text='Email or phone number', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='ImportantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('document_category', models.CharField(choices=[('Allergies and Sensitivities', 'Summary of known allergies and sensitivities.'), ('Assisted Living or Nursing Home Info', 'Information about facilities, contracts, and preferences.'), ('Budget and Recurring Bills', 'List of monthly bills, due dates, and payment methods.'), ('Business Ownership Documents', 'Ownership records, operating agreements, and related business documents.'), ('Care Preferences at Home', 'Preferences for in-home care, routines, and services.'), ('Charitable Giving Plans', 'Information on current and planned charitable giving.'), ('Cloud Storage Accounts', 'Logins and notes for cloud storage services.'), ('Credit Card Accounts', 'List of credit card accounts and issuers.'), ('Current Medications', 'List of current prescriptions and dosages.'), ('Debts and Liabilities', 'List of outstanding debts, including creditors and terms.'), ('Dependents and Care Needs', 'Information on dependents and their specific care needs.'), ('Digital Subscriptions and Services', 'Online services and subscriptions with access details.'), ('Disability Insurance Policies', 'Policies providing income in case of disability.'), ('Email Accounts', 'Addresses and access details for email accounts.'), ('Funeral and Burial Wishes', 'Preferences for funeral, burial, or cremation.'), ('Health Insurance Policies', 'Policies providing medical coverage.'), ('Important Personal Documents', 'Birth certificate, marriage certificate, etc.'), ('In-Home Care Providers', 'Contact information for in-home care professionals.'), ('Income Sources', 'Employment, pensions, annuities, and other income.'), ('Insurance Policies', 'Life, disability, and other policies relevant to your estate and survivors.'), ('Investment Accounts', 'Brokerage and other investment account information.'), ('Life Insurance Policies', 'Policies paying a benefit upon death.'), ('Loans and Mortgages', 'Details of personal loans and mortgages.'), ('Long-Term Care Insurance', 'Policies covering long-term care needs.'), ('Medical History', 'Summary of past diagnoses, surgeries, and major medical events.'), ('Medical Specialists', 'Contact information for medical specialists.'), ('Medicare / Medicaid Information', 'Coverage details and identification numbers.'), ('Membership and Affiliations', 'Clubs, organizations, and professional memberships.'), ('Memorial Instructions', 'Preferences for memorial services and gatherings.'), ('Notes and Special Instructions', 'Additional notes and instructions not covered elsewhere.'), ('Online Accounts and Passwords', 'List of online services and passwords.'), ('Online Banking and Finance Logins', 'Credentials and notes for online financial accounts.'), ('Password Manager Information', 'Access information for password manager accounts.'), ('Pensions and Annuities', 'Information on pension plans and annuity contracts.'), ('Personal Identification', "Driver's license, passport, and other ID."), ('Personal Property and Valuables', 'Inventory of important personal items and valuables.'), ('Pet Care and Ownership', 'Information and instructions regarding pets.'), ('Primary Bank Accounts', 'Main checking and savings account details.'), ('Primary Physician Information', 'Contact details for primary care physician.'), ('Property Deeds and Titles', 'Deeds, titles, and related ownership documents for real estate and vehicles.'), ('Real Estate Documents', 'Deeds, surveys, and related property records.'), ('Retirement Accounts', '401(k), IRA, and other retirement account details.'), ('Safe Deposit Box Information', 'Location, access, and contents of safe deposit boxes.'), ('Social Media Accounts', 'Accounts and preferences for social media platforms.'), ('Social Security Information', 'Social Security number and benefit information.'), ('Tax Returns and Records', 'Recent tax returns and related records.'), ('Vehicle Titles and Registration', 'Vehicle title and registration documents.')], default='important_personal_documents', max_length=50)),
                ('physical_location', models.CharField(blank=True, help_text='Where physical document is stored', max_length=200)),
                ('digital_location', models.CharField(blank=True, help_text='Where digital copy is stored', max_length=500)),
                ('file', models.FileField(blank=True, help_text='Upload digital copy', null=True, upload_to='documents/%Y/%m/')),
                ('requires_legal_review', models.BooleanField(default=False, help_text='Needs legal professional review')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, help_text='Contact this document is primarily associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='important_documents', to='dashboard.contact')),
                ('profile', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='important_documents', to='dashboard.profile')),
            ],
            options={
                'db_table': 'important_documents',
                'ordering': ['document_category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DigitalEstateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estate_document', models.CharField(choices=[('Healthcare Documents', [('Advance Directive / Living Will', 'Advance Directive / Living Will — States your wishes for end-of-life or critical medical care.'), ('Durable Power of Attorney for Healthcare', 'Durable Power of Attorney for Healthcare — Authorizes someone to make medical decisions if you cannot.'), ('Living Will / Advance Directive', 'Living Will / Advance Directive — States your wishes for end-of-life or critical medical care.'), ('HIPAA Authorizations', 'HIPAA Authorizations — Allows named individuals to access your medical information.'), ('Organ Donation Preferences', 'Organ Donation Preferences — Documents or forms stating your organ donation wishes.')]), ('Financial and Legal Documents', [('Durable Power of Attorney for Financial Matters', 'Durable Power of Attorney for Financial Matters — Authorizes someone to manage finances if you are incapacitated.'), ('Beneficiary Designations', 'Beneficiary Designations — Forms for life insurance, retirement accounts, etc., naming who receives benefits.'), ('Guardianship Designations', 'Guardianship Designations — Documents naming guardians for minor children or dependents.'), ('Trust Documents', 'Trust Documents — Revocable or irrevocable trust agreements holding and distributing property.')]), ('Estate Administration and Final Instructions', [('Executor / Personal Representative Info', 'Executor / Personal Representative Info — Information about the person(s) designated to administer your estate.'), ('Letter of Instruction', 'Letter of Instruction — Provides guidance for heirs, location of assets, and personal wishes.'), ('Will and Codicils', 'Will and Codicils — Last Will and Testament and any amendments (codicils).')])], default='important_personal_documents', max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Is this the current active document?')),
                ('overall_instructions', models.CharField(blank=True, help_text='General instructions for family', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, help_text='Contact this estate document is primarily associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estate_documents', to='dashboard.contact')),
                ('profile', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='estate_documents', to='dashboard.profile')),
            ],
            options={
                'db_table': 'digital_estate_documents',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('phone', 'Phone'), ('tablet', 'Tablet'), ('laptop', 'Laptop'), ('desktop', 'Desktop'), ('smartwatch', 'Smart Watch'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(help_text='Device name or model', max_length=200)),
                ('owner_label', models.CharField(blank=True, help_text="e.g., 'Mom's iPhone', 'Work Laptop'", max_length=100)),
                ('location_description', models.CharField(blank=True, help_text='Where device is typically kept', max_length=200)),
                ('unlock_method_description', models.CharField(blank=True, help_text='How to unlock (without revealing actual password)', max_length=200)),
                ('used_for_2fa', models.BooleanField(default=False)),
                ('decommission_instruction', models.TextField(blank=True, help_text='What to do with this device after death')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='dashboard.profile')),
            ],
            options={
                'db_table': 'devices',
                'ordering': ['device_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DelegationGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delegation_category', models.CharField(choices=[('MEDICAL_TREATMENT_DECISIONS', 'Healthcare Decision-Making'), ('FINANCIAL_AUTHORITY', 'Financial Authority'), ('ESTATE_AND_PROPERTY_OVERSIGHT', 'Estate and Property Oversight'), ('PERSONAL_AND_FAMILY_AFFAIRS', 'Personal and Family Affairs')], default='Healthcare Decision-Making', max_length=200)),
                ('applies_on_death', models.BooleanField(default=False)),
                ('applies_on_incapacity', models.BooleanField(default=False)),
                ('applies_immediately', models.BooleanField(default=False)),
                ('notes_for_contact', models.TextField(blank=True, help_text='Instructions for the contact')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delegate_to', models.ForeignKey(blank=True, help_text='Contact receiving this delegation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delegation_grants', to='dashboard.contact')),
                ('delegate_estate_documents', models.ManyToManyField(blank=True, help_text='Estate documents this delegation covers', related_name='delegation_grants', to='dashboard.digitalestatedocument')),
                ('delegate_important_documents', models.ManyToManyField(blank=True, help_text='Important documents this delegation covers', related_name='delegation_grants', to='dashboard.importantdocument')),
                ('profile', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='delegation_grants', to='dashboard.profile')),
            ],
            options={
                'db_table': 'delegation_grants',
                'ordering': ['delegate_to', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='profile',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='relation_contacts', to='dashboard.profile'),
        ),
        migrations.CreateModel(
            name='Checkup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi-annual', 'Semi-Annual'), ('annual', 'Annual')], max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('all_accounts_reviewed', models.BooleanField(default=False)),
                ('all_devices_reviewed', models.BooleanField(default=False)),
                ('contacts_up_to_date', models.BooleanField(default=False)),
                ('documents_up_to_date', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_checkups', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='checkups', to='dashboard.profile')),
            ],
            options={
                'db_table': 'checkups',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='CareRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('caregiver', 'Caregiver'), ('healthcare-proxy', 'Healthcare Proxy'), ('power-of-attorney', 'Power of Attorney'), ('trustee', 'Trustee'), ('other', 'Other')], max_length=30)),
                ('has_portal_access', models.BooleanField(default=False, help_text='Has access to digital estate portal')),
                ('portal_role', models.CharField(blank=True, choices=[('view-only', 'View Only'), ('editor', 'Editor'), ('admin', 'Administrator')], default='view-only', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_relationships', to='dashboard.contact')),
                ('profile', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='care_relationships', to='dashboard.profile')),
            ],
            options={
                'db_table': 'care_relationships',
                'ordering': ['contact_name'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='profile',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='dashboard.profile'),
        ),
        migrations.CreateModel(
            name='RecoveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_description', models.CharField(help_text='Description of account to recover', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('denied', 'Denied'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('provider_ticket_number', models.CharField(blank=True, max_length=100)),
                ('steps_taken', models.TextField(blank=True)),
                ('outcome_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='recovery_requests', to='dashboard.profile')),
                ('requested_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='recovery_requests_made', to=settings.AUTH_USER_MODEL)),
                ('target_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recovery_requests', to='dashboard.account')),
            ],
            options={
                'db_table': 'recovery_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['profile', '-created_at'], name='accounts_profile_bd7b53_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_category'], name='accounts_account_0ed7bc_idx'),
        ),
    ]
