# Generated by Django 6.0.1 on 2026-01-08 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CheckupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('frequency', models.CharField(choices=[('QUARTERLY', 'Quarterly'), ('ANNUAL', 'Annual'), ('ONE_OFF', 'One-off')], max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200)),
                ('relationship', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('is_emergency_contact', models.BooleanField(default=False)),
                ('is_digital_executor', models.BooleanField(default=False)),
                ('is_caregiver', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='DelegationScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalEstateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Digital Estate Instructions', max_length=200)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('overall_instructions', models.TextField()),
                ('location_of_legal_will', models.CharField(blank=True, max_length=255)),
                ('location_of_password_manager_instructions', models.CharField(blank=True, max_length=255)),
                ('wishes_for_social_media', models.TextField(blank=True)),
                ('wishes_for_photos_and_files', models.TextField(blank=True)),
                ('data_retention_preferences', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DigitalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('provider', models.CharField(blank=True, max_length=200)),
                ('website_url', models.URLField(blank=True)),
                ('username_or_email', models.CharField(blank=True, max_length=255)),
                ('credential_storage_location', models.CharField(blank=True, help_text='Where to find login credentials (password manager, safe, etc.).', max_length=255)),
                ('is_critical', models.BooleanField(default=True)),
                ('keep_or_close_instruction', models.CharField(choices=[('KEEP', 'Keep active'), ('CLOSE', 'Close after estate settlement'), ('MEMORIALIZE', 'Memorialize'), ('UNSURE', 'Unsure / needs review')], default='KEEP', max_length=50)),
                ('notes_for_family', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='dashboard.accountcategory')),
            ],
            options={
                'ordering': ['-is_critical', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AccountRelevanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matters', models.BooleanField()),
                ('reasoning', models.TextField(blank=True)),
                ('next_review_due', models.DateField(blank=True, null=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_relevance_reviews', to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relevance_reviews', to='dashboard.digitalaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyNeedsToKnowSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('content', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_sections', to='dashboard.digitalestatedocument')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('primary_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('has_digital_executor', models.BooleanField(default=False)),
                ('digital_executor_name', models.CharField(blank=True, max_length=200)),
                ('digital_executor_contact', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estate Profile',
                'verbose_name_plural': 'Estate Profiles',
            },
        ),
        migrations.CreateModel(
            name='ImportantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('physical_location', models.CharField(blank=True, max_length=255)),
                ('digital_location', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='estate_documents/')),
                ('requires_legal_review', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='dashboard.documentcategory')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='important_documents', to='dashboard.profile')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_notes', to='dashboard.contact')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_notes', to='dashboard.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='digitalestatedocument',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_estate_documents', to='dashboard.profile'),
        ),
        migrations.AddField(
            model_name='digitalaccount',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='dashboard.profile'),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_type', models.CharField(choices=[('PHONE', 'Phone'), ('TABLET', 'Tablet'), ('LAPTOP', 'Laptop'), ('DESKTOP', 'Desktop'), ('SERVER', 'Server/NAS'), ('OTHER', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('operating_system', models.CharField(blank=True, max_length=100)),
                ('owner_label', models.CharField(blank=True, max_length=100)),
                ('location_description', models.CharField(blank=True, max_length=255)),
                ('unlock_method_description', models.CharField(blank=True, max_length=255)),
                ('has_full_disk_encryption', models.BooleanField(default=True)),
                ('used_for_2fa', models.BooleanField(default=False)),
                ('decommission_instruction', models.CharField(blank=True, max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='dashboard.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='dashboard.profile'),
        ),
        migrations.CreateModel(
            name='Checkup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('all_accounts_reviewed', models.BooleanField(default=False)),
                ('all_devices_reviewed', models.BooleanField(default=False)),
                ('contacts_up_to_date', models.BooleanField(default=False)),
                ('documents_up_to_date', models.BooleanField(default=False)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_checkups', to=settings.AUTH_USER_MODEL)),
                ('checkup_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkups', to='dashboard.checkuptype')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkups', to='dashboard.profile')),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='AccountDirectoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=200)),
                ('category_label', models.CharField(blank=True, max_length=100)),
                ('website_url', models.URLField(blank=True)),
                ('username_hint', models.CharField(blank=True, max_length=255)),
                ('criticality', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='HIGH', max_length=20)),
                ('action_after_death', models.CharField(choices=[('KEEP', 'Keep'), ('CLOSE', 'Close'), ('MEMORIALIZE', 'Memorialize'), ('ARCHIVE', 'Archive data only')], default='KEEP', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directory_entries', to='dashboard.profile')),
            ],
            options={
                'ordering': ['-criticality', 'label'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_description', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('RESOLVED', 'Resolved'), ('FAILED', 'Failed / not possible')], default='OPEN', max_length=20)),
                ('provider_ticket_number', models.CharField(blank=True, max_length=100)),
                ('steps_taken', models.TextField(blank=True)),
                ('outcome_notes', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_requests', to='dashboard.profile')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_requests', to='dashboard.contact')),
                ('target_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_requests', to='dashboard.digitalaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='digitalestatedocument',
            unique_together={('profile', 'version')},
        ),
        migrations.CreateModel(
            name='DelegationGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applies_on_death', models.BooleanField(default=True)),
                ('applies_on_incapacity', models.BooleanField(default=True)),
                ('applies_immediately', models.BooleanField(default=False)),
                ('notes_for_contact', models.TextField(blank=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='dashboard.contact')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='dashboard.delegationscope')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='dashboard.profile')),
            ],
            options={
                'unique_together': {('profile', 'contact', 'scope')},
            },
        ),
        migrations.CreateModel(
            name='CareRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship_type', models.CharField(choices=[('SPOUSE', 'Spouse/Partner'), ('CAREGIVER', 'Caregiver'), ('POA', 'Power of Attorney'), ('TRUSTEE', 'Trustee'), ('OTHER', 'Other')], max_length=50)),
                ('has_portal_access', models.BooleanField(default=False)),
                ('portal_role', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_relationships', to='dashboard.contact')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_relationships', to='dashboard.profile')),
            ],
            options={
                'unique_together': {('profile', 'contact', 'relationship_type')},
            },
        ),
    ]
