# Generated by Django 6.0.1 on 2026-01-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='used_for_2fa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='importantdocument',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='importantdocument',
            name='physical_location',
            field=models.CharField(blank=True, help_text='Where physical document is stored', max_length=200),
        ),
    ]
