# Generated by Django 6.0.1 on 2026-02-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_financial_agent',
            field=models.BooleanField(default=False, help_text='Authorized under financial power of attorney to handle money/bills if incapacitated.'),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_guardian_for_dependents',
            field=models.BooleanField(default=False, help_text='Named legal guardian for minor children or dependent adults.'),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_healthcare_proxy',
            field=models.BooleanField(default=False, help_text="Makes medical decisions if you're unable to communicate (healthcare power of attorney)."),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_knowledge_contact',
            field=models.BooleanField(default=False, help_text='Delegated specific knowledge/info (e.g., account locations) but no action required.'),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_legacy_contact',
            field=models.BooleanField(default=False, help_text='Designated for platform-specific legacy access (e.g., Apple, Google, Facebook).'),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_legal_executor',
            field=models.BooleanField(default=False, help_text='Named executor/personal representative to administer overall estate and will.'),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_memorial_contact',
            field=models.BooleanField(default=False, help_text='Handles funeral, memorial service, and burial/cremation preferences.'),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_notification_only',
            field=models.BooleanField(default=False, help_text='Receives notifications and basic info but has no decision-making authority or tasks.'),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_pet_caregiver',
            field=models.BooleanField(default=False, help_text='Responsible for pet care, veterinary decisions, and related expenses.'),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_professional_advisor',
            field=models.BooleanField(default=False, help_text='Attorney, accountant, or advisor to consult for legal/financial guidance.'),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_trustee',
            field=models.BooleanField(default=False, help_text='Manages trusts, distributions, and trust assets according to trust terms.'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_caregiver',
            field=models.BooleanField(default=False, help_text='Primary person providing or coordinating long-term care needs and health decisions.'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_digital_executor',
            field=models.BooleanField(default=False, help_text='Responsible for managing digital assets (accounts, passwords, online services) after death.'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_emergency_contact',
            field=models.BooleanField(default=False, help_text='Contact to notify and provide access during medical emergencies or sudden incapacity.'),
        ),
    ]
