# Generated by Django 4.2.9 on 2026-01-23 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountrelevancereview',
            name='account_relevance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relevance_reviews', to='dashboard.account'),
        ),
    ]
