# Generated by Django 6.0.1 on 2026-02-06 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegationgrant',
            name='delegate_to',
            field=models.ForeignKey(help_text='Contact receiving this delegation', on_delete=django.db.models.deletion.CASCADE, related_name='delegation_grants', to='dashboard.contact'),
        ),
    ]
