# Generated by Django 5.2.11 on 2026-02-26 19:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_financial_agent',
            field=models.BooleanField(default=False, help_text='Authorized under financial power of attorney to handle money/bills if incapacitated.'),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_guardian_for_dependents',
            field=models.BooleanField(default=False, help_text='Named legal guardian for minor children or dependent adults.'),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_healthcare_proxy',
            field=models.BooleanField(default=False, help_text="Makes medical decisions if you're unable to communicate (healthcare power of attorney)."),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_knowledge_contact',
            field=models.BooleanField(default=False, help_text='Delegated specific knowledge/info (e.g., account locations) but no action required.'),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_legacy_contact',
            field=models.BooleanField(default=False, help_text='Designated for platform-specific legacy access (e.g., Apple, Google, Facebook).'),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_legal_executor',
            field=models.BooleanField(default=False, help_text='Named executor/personal representative to administer overall estate and will.'),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_memorial_contact',
            field=models.BooleanField(default=False, help_text='Handles funeral, memorial service, and burial/cremation preferences.'),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_notification_only',
            field=models.BooleanField(default=False, help_text='Receives notifications and basic info but has no decision-making authority or tasks.'),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_pet_caregiver',
            field=models.BooleanField(default=False, help_text='Responsible for pet care, veterinary decisions, and related expenses.'),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_professional_advisor',
            field=models.BooleanField(default=False, help_text='Attorney, accountant, or advisor to consult for legal/financial guidance.'),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_trustee',
            field=models.BooleanField(default=False, help_text='Manages trusts, distributions, and trust assets according to trust terms.'),
        ),
        migrations.AlterField(
            model_name='account',
            name='keep_or_close_instruction',
            field=models.CharField(choices=[('Close Account', 'Close Account'), ('Keep Active', 'Keep Active'), ('Memorialize', 'Memorialize'), ('Other (See Notes)', 'Other (See Notes)')], default='Keep Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='review_time',
            field=models.PositiveSmallIntegerField(choices=[(30, '30 Days (One Month)'), (60, '60 Days (2 Months)'), (90, '90 Days (3 Months)'), (180, '180 Days (6 Months)'), (365, '365 Days (1 Year)')], default=30, help_text='How often would you like to review this item (Email Notification will be sent)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='website_url',
            field=models.URLField(blank=True, help_text='Format must use https://www.example.com to validate, leave blank if unsure', validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_caregiver',
            field=models.BooleanField(default=False, help_text='Primary person providing or coordinating long-term care needs and health decisions.'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_digital_executor',
            field=models.BooleanField(default=False, help_text='Responsible for managing digital assets (accounts, passwords, online services) after death.'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_emergency_contact',
            field=models.BooleanField(default=False, help_text='Contact to notify and provide access during medical emergencies or sudden incapacity.'),
        ),
        migrations.AlterField(
            model_name='device',
            name='review_time',
            field=models.PositiveSmallIntegerField(choices=[(30, '30 Days (One Month)'), (60, '60 Days (2 Months)'), (90, '90 Days (3 Months)'), (180, '180 Days (6 Months)'), (365, '365 Days (1 Year)')], default=30, help_text='How often would you like to review this item (Email Notification will be sent)'),
        ),
        migrations.AlterField(
            model_name='digitalestatedocument',
            name='review_time',
            field=models.PositiveSmallIntegerField(choices=[(30, '30 Days (One Month)'), (60, '60 Days (2 Months)'), (90, '90 Days (3 Months)'), (180, '180 Days (6 Months)'), (365, '365 Days (1 Year)')], default=30, help_text='How often would you like to review this item (Email Notification will be sent)'),
        ),
        migrations.AlterField(
            model_name='importantdocument',
            name='review_time',
            field=models.PositiveSmallIntegerField(choices=[(30, '30 Days (One Month)'), (60, '60 Days (2 Months)'), (90, '90 Days (3 Months)'), (180, '180 Days (6 Months)'), (365, '365 Days (1 Year)')], default=30, help_text='How often would you like to review this item (Email Notification will be sent)'),
        ),
        migrations.CreateModel(
            name='FuneralPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_name', models.CharField(blank=True, help_text='Nickname or preferred name to use in service/obituary.', max_length=100)),
                ('occupation', models.CharField(blank=True, help_text='Current or former occupation to include in obituary.', max_length=200)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced'), ('Separated', 'Separated'), ('Domestic Partnership', 'Domestic Partnership'), ('Prefer Not to Say', 'Prefer Not to Say')], max_length=50)),
                ('religion_or_spiritual_affiliation', models.CharField(blank=True, help_text='Religion, denomination, or spiritual tradition (if any).', max_length=200)),
                ('is_veteran', models.BooleanField(default=False, help_text='Did the person serve in the military?')),
                ('veteran_branch', models.CharField(blank=True, help_text='Branch of military service (e.g., Army, Navy, Air Force).', max_length=100)),
                ('service_type', models.CharField(blank=True, choices=[('Traditional Funeral', 'Traditional Funeral'), ('Memorial Service', 'Memorial Service'), ('Graveside Service', 'Graveside Service'), ('Celebration of Life', 'Celebration of Life'), ('Private / Family Only', 'Private / Family Only'), ('No Service', 'No Service'), ('Other', 'Other')], max_length=50)),
                ('preferred_funeral_home', models.CharField(blank=True, help_text='Name of preferred funeral home or funeral director.', max_length=200)),
                ('funeral_home_phone', models.CharField(blank=True, max_length=20)),
                ('funeral_home_address', models.CharField(blank=True, max_length=300)),
                ('preferred_venue', models.CharField(blank=True, help_text='Preferred location for the service (funeral home, church, outdoors, etc.).', max_length=300)),
                ('officiant_name_freetext', models.CharField(blank=True, help_text='Officiant name if not yet in contacts.', max_length=200)),
                ('desired_timing', models.CharField(blank=True, choices=[('Weekday - Daytime', 'Weekday - Daytime'), ('Weekday - Evening', 'Weekday - Evening'), ('Weekend - Daytime', 'Weekend - Daytime'), ('Weekend - Evening', 'Weekend - Evening'), ('No Preference', 'No Preference')], max_length=50)),
                ('open_casket_viewing', models.CharField(blank=True, choices=[('Yes - Open Casket', 'Yes - Open Casket'), ('Family Only', 'Family Only'), ('No Viewing', 'No Viewing'), ('No Preference', 'No Preference')], max_length=50)),
                ('disposition_method', models.CharField(blank=True, choices=[('Burial', 'Burial'), ('Cremation', 'Cremation'), ('Green / Natural Burial', 'Green / Natural Burial'), ('Donation to Science', 'Donation to Science'), ('Other', 'Other'), ('No Preference', 'No Preference')], max_length=50)),
                ('burial_or_interment_location', models.CharField(blank=True, help_text='Cemetery name, columbarium, or scatter site.', max_length=300)),
                ('burial_plot_or_niche_purchased', models.BooleanField(blank=True, help_text='Has a burial plot or cremation niche already been purchased?', null=True)),
                ('casket_type_preference', models.CharField(blank=True, help_text='Casket material or style preference (e.g., wood, eco-friendly, simple).', max_length=200)),
                ('urn_type_preference', models.CharField(blank=True, help_text='Urn style or material preference (if cremation).', max_length=200)),
                ('headstone_or_marker_inscription', models.TextField(blank=True, help_text='Ideas or wording for a headstone, marker, or memorial plaque.')),
                ('music_choices', models.TextField(blank=True, help_text='Songs, hymns, performers, or instruments desired at the service.')),
                ('flowers_or_colors', models.CharField(blank=True, help_text='Preferred flowers, arrangements, or color palette.', max_length=300)),
                ('readings_poems_or_scriptures', models.TextField(blank=True, help_text='Specific readings, poems, or scripture passages to be included.')),
                ('eulogists_notes', models.TextField(blank=True, help_text='Names of desired eulogists or speakers, and topics to address.')),
                ('pallbearers_notes', models.TextField(blank=True, help_text='Desired pallbearers (names or relationship descriptions).')),
                ('clothing_or_jewelry_description', models.CharField(blank=True, help_text='What clothing or jewelry the deceased should be dressed in.', max_length=300)),
                ('religious_cultural_customs', models.TextField(blank=True, help_text='Religious rites, cultural traditions, or customs to observe.')),
                ('items_to_display', models.TextField(blank=True, help_text='Photos, memorabilia, military flag, hobby items, or other displays.')),
                ('reception_desired', models.BooleanField(blank=True, help_text='Is a post-service gathering or reception desired?', null=True)),
                ('reception_location', models.CharField(blank=True, max_length=300)),
                ('reception_food_preferences', models.TextField(blank=True, help_text='Catering style, dietary notes, or specific food/drink preferences.')),
                ('reception_atmosphere_notes', models.TextField(blank=True, help_text='Music, ambiance, or atmosphere preferences for the reception.')),
                ('reception_guest_list_notes', models.TextField(blank=True, help_text='Notes on invitations, guest list scope, or who to notify.')),
                ('obituary_photo_description', models.CharField(blank=True, help_text='Description or location of preferred photo for obituary/service.', max_length=300)),
                ('obituary_key_achievements', models.TextField(blank=True, help_text='Key life achievements, milestones, or memories to highlight.')),
                ('obituary_publications', models.TextField(blank=True, help_text='Newspapers, websites, or platforms to publish the obituary.')),
                ('charitable_donations_in_lieu', models.CharField(blank=True, help_text='Charity or cause to suggest in lieu of flowers.', max_length=300)),
                ('funeral_insurance_policy_number', models.CharField(blank=True, help_text='Pre-paid funeral plan or funeral insurance policy number.', max_length=100)),
                ('death_certificates_requested', models.PositiveSmallIntegerField(blank=True, help_text='Number of certified death certificate copies needed (typically 6-12).', null=True)),
                ('payment_arrangements', models.TextField(blank=True, help_text='Funding source or payment arrangements for funeral expenses.')),
                ('additional_instructions', models.TextField(blank=True, help_text='Any other instructions, requests, or personal messages to family.')),
                ('review_time', models.PositiveSmallIntegerField(choices=[(30, '30 Days (One Month)'), (60, '60 Days (2 Months)'), (90, '90 Days (3 Months)'), (180, '180 Days (6 Months)'), (365, '365 Days (1 Year)')], default=365, help_text='How often to send a reminder email to review this plan.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('officiant_contact', models.ForeignKey(blank=True, help_text='Clergy, celebrant, or officiant from your contacts list.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officiant_for_plans', to='dashboard.contact')),
                ('profile', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='funeral_plan', to='dashboard.profile')),
            ],
            options={
                'db_table': 'funeral_plans',
                'ordering': ['-updated_at'],
            },
        ),
    ]
