# Generated by Django 6.0.1 on 2026-01-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountcategory',
            options={'ordering': ['user', 'name'], 'verbose_name_plural': 'Account categories'},
        ),
        migrations.RemoveField(
            model_name='accountcategory',
            name='sort_order',
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
