# Generated by Django 6.0.1 on 2026-02-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address_1',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address_2',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='state',
            field=models.CharField(),
        ),
    ]
