# Generated by Django 6.0.1 on 2026-02-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='review_time',
            field=models.CharField(choices=[(30, '30 Days (One Month)'), (60, '60 Days (2 Months)'), (90, '90 Days (3 Months)'), (180, '180 Days (6 Months)'), (365, '365 Days (1 Year)')], default='30', max_length=100),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='frequency',
            field=models.CharField(choices=[(30, '30 Days (One Month)'), (60, '60 Days (2 Months)'), (90, '90 Days (3 Months)'), (180, '180 Days (6 Months)'), (365, '365 Days (1 Year)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='review_time',
            field=models.PositiveSmallIntegerField(choices=[(30, '30 Days (One Month)'), (60, '60 Days (2 Months)'), (90, '90 Days (3 Months)'), (180, '180 Days (6 Months)'), (365, '365 Days (1 Year)')], default=30),
        ),
        migrations.AlterField(
            model_name='digitalestatedocument',
            name='review_time',
            field=models.CharField(choices=[(30, '30 Days (One Month)'), (60, '60 Days (2 Months)'), (90, '90 Days (3 Months)'), (180, '180 Days (6 Months)'), (365, '365 Days (1 Year)')], default='30', max_length=100),
        ),
        migrations.AlterField(
            model_name='importantdocument',
            name='review_time',
            field=models.CharField(choices=[(30, '30 Days (One Month)'), (60, '60 Days (2 Months)'), (90, '90 Days (3 Months)'), (180, '180 Days (6 Months)'), (365, '365 Days (1 Year)')], default='30', max_length=100),
        ),
    ]
