# Generated by Django 6.0.1 on 2026-02-16 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carerelationship',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='carerelationship',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='checkup',
            name='completed_by',
        ),
        migrations.RemoveField(
            model_name='checkup',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='recoveryrequest',
            name='requested_by',
        ),
        migrations.AddField(
            model_name='recoveryrequest',
            name='additional_notes',
            field=models.TextField(blank=True, help_text='Additional information supporting the request'),
        ),
        migrations.AddField(
            model_name='recoveryrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recoveryrequest',
            name='death_certificate',
            field=models.FileField(blank=True, help_text='Death certificate or medical documentation', null=True, upload_to='recovery_requests/certificates/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='recoveryrequest',
            name='legal_authorization',
            field=models.FileField(blank=True, help_text='Power of attorney, executor documentation, court order, etc.', null=True, upload_to='recovery_requests/legal/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='recoveryrequest',
            name='proof_of_relationship',
            field=models.FileField(blank=True, help_text='Proof of relationship (e.g., marriage certificate, birth certificate)', null=True, upload_to='recovery_requests/proof/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='recoveryrequest',
            name='reason',
            field=models.CharField(choices=[('Death', 'Account owner is deceased'), ('Incapacitation', 'Account owner is incapacitated'), ('Other', 'Other circumstance')], default='Death', max_length=20),
        ),
        migrations.AddField(
            model_name='recoveryrequest',
            name='requested_by_user',
            field=models.ForeignKey(blank=True, help_text='Authenticated user making the request (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_requests_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recoveryrequest',
            name='requester_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='recoveryrequest',
            name='requester_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recoveryrequest',
            name='requester_last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recoveryrequest',
            name='requester_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='recoveryrequest',
            name='requester_relationship',
            field=models.CharField(blank=True, help_text='Relationship to account owner', max_length=50),
        ),
        migrations.AddField(
            model_name='recoveryrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recoveryrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who reviewed this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_recovery_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recoveryrequest',
            name='verification_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recoveryrequest',
            name='verification_token',
            field=models.CharField(blank=True, editable=False, help_text="Token sent to requester's email for verification", max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='recoveryrequest',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recoveryrequest',
            name='outcome_notes',
            field=models.TextField(blank=True, help_text='Final outcome and resolution details'),
        ),
        migrations.AlterField(
            model_name='recoveryrequest',
            name='profile',
            field=models.ForeignKey(editable=False, help_text='Profile of the deceased/incapacitated user', on_delete=django.db.models.deletion.CASCADE, related_name='recovery_requests', to='dashboard.profile'),
        ),
        migrations.AlterField(
            model_name='recoveryrequest',
            name='provider_ticket_number',
            field=models.CharField(blank=True, help_text='External service provider ticket/case number', max_length=100),
        ),
        migrations.AlterField(
            model_name='recoveryrequest',
            name='status',
            field=models.CharField(choices=[('Pending Verification', 'Pending Verification'), ('Verified', 'Verified'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Denied', 'Denied'), ('Cancelled', 'Cancelled')], default='Pending Verification', max_length=25),
        ),
        migrations.AlterField(
            model_name='recoveryrequest',
            name='steps_taken',
            field=models.TextField(blank=True, help_text='Actions taken to process this request'),
        ),
        migrations.AlterField(
            model_name='recoveryrequest',
            name='target_account',
            field=models.ForeignKey(blank=True, help_text='Specific account to recover (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_requests', to='dashboard.account'),
        ),
        migrations.AlterField(
            model_name='recoveryrequest',
            name='target_description',
            field=models.CharField(help_text='Description of what needs to be recovered', max_length=500),
        ),
        migrations.AddIndex(
            model_name='recoveryrequest',
            index=models.Index(fields=['status', '-created_at'], name='recovery_re_status_41ec4e_idx'),
        ),
        migrations.AddIndex(
            model_name='recoveryrequest',
            index=models.Index(fields=['verification_token'], name='recovery_re_verific_428f8f_idx'),
        ),
        migrations.AddIndex(
            model_name='recoveryrequest',
            index=models.Index(fields=['requester_email'], name='recovery_re_request_a62e7e_idx'),
        ),
        migrations.DeleteModel(
            name='CareRelationship',
        ),
        migrations.DeleteModel(
            name='Checkup',
        ),
    ]
