# Generated by Django 6.0.1 on 2026-02-19 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_contact_is_financial_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='keep_or_close_instruction',
            field=models.CharField(choices=[('Close Account', 'Close Account'), ('Keep Active', 'Keep Active'), ('Memorialize', 'Memorialize'), ('Other (See Notes)', 'Other (See Notes)')], default='Keep Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='review_time',
            field=models.PositiveSmallIntegerField(choices=[(30, '30 Days (One Month)'), (60, '60 Days (2 Months)'), (90, '90 Days (3 Months)'), (180, '180 Days (6 Months)'), (365, '365 Days (1 Year)')], default=30, help_text='How often would you like to review this item (Email Notification will be sent)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='website_url',
            field=models.URLField(blank=True, help_text='Format must use https://www.example.com to validate, leave blank if unsure', validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='device',
            name='review_time',
            field=models.PositiveSmallIntegerField(choices=[(30, '30 Days (One Month)'), (60, '60 Days (2 Months)'), (90, '90 Days (3 Months)'), (180, '180 Days (6 Months)'), (365, '365 Days (1 Year)')], default=30, help_text='How often would you like to review this item (Email Notification will be sent)'),
        ),
        migrations.AlterField(
            model_name='digitalestatedocument',
            name='review_time',
            field=models.PositiveSmallIntegerField(choices=[(30, '30 Days (One Month)'), (60, '60 Days (2 Months)'), (90, '90 Days (3 Months)'), (180, '180 Days (6 Months)'), (365, '365 Days (1 Year)')], default=30, help_text='How often would you like to review this item (Email Notification will be sent)'),
        ),
        migrations.AlterField(
            model_name='importantdocument',
            name='review_time',
            field=models.PositiveSmallIntegerField(choices=[(30, '30 Days (One Month)'), (60, '60 Days (2 Months)'), (90, '90 Days (3 Months)'), (180, '180 Days (6 Months)'), (365, '365 Days (1 Year)')], default=30, help_text='How often would you like to review this item (Email Notification will be sent)'),
        ),
    ]
