# Generated by Django 6.0.1 on 2026-02-16 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_carerelationship_contact_name_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='recoveryrequest',
            name='recovery_re_status_41ec4e_idx',
        ),
        migrations.RemoveIndex(
            model_name='recoveryrequest',
            name='recovery_re_verific_428f8f_idx',
        ),
        migrations.RemoveIndex(
            model_name='recoveryrequest',
            name='recovery_re_request_a62e7e_idx',
        ),
        migrations.DeleteModel(
            name='RecoveryRequest',
        ),
    ]
