# Generated by Django 6.0.1 on 2026-01-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_device_used_for_2fa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalestatedocument',
            name='data_retention_preferences',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='digitalestatedocument',
            name='location_of_legal_will',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='digitalestatedocument',
            name='location_of_password_manager_instructions',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='digitalestatedocument',
            name='overall_instructions',
            field=models.CharField(blank=True, help_text='General instructions for family'),
        ),
        migrations.AlterField(
            model_name='digitalestatedocument',
            name='wishes_for_photos_and_files',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='digitalestatedocument',
            name='wishes_for_social_media',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
