# Generated by Django 6.0.1 on 2026-02-06 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_delegationgrant_delegate_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegationgrant',
            name='delegate_to',
            field=models.ForeignKey(help_text='Contact receiving this delegation', on_delete=django.db.models.deletion.DO_NOTHING, related_name='delegation_grants', to='dashboard.contact'),
        ),
        migrations.AlterField(
            model_name='delegationgrant',
            name='profile',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='delegation_grants', to='dashboard.profile'),
        ),
    ]
