# Generated by Django 6.0.1 on 2026-02-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_contact_address_1_alter_contact_address_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_category',
            field=models.CharField(choices=[('App Store Account', 'App Store'), ('Brokerage/Investment Account', 'Brokerage/Investment'), ('Cloud Storage Account', 'Cloud Storage'), ('Cryptocurrency Exchange Account', 'Cryptocurrency Exchange'), ('Ecommerce Marketplace Account', 'Ecommerce Marketplace'), ('Education/Elearning Account', 'Education or Elearning'), ('Email Account', 'Email'), ('Forum/Community Account', 'Forum/Community'), ('Gaming Platform Account', 'Gaming Platform'), ('Government Portal Account', 'Government Portal'), ('Health Portal Account', 'Health Portal'), ('Neobank/Digital Bank Account', 'Neobank/Digital Bank'), ('Online Banking Account', 'Online Banking'), ('Password Manager Account', 'Password Manager'), ('Payment Processor Account', 'Payment Processor'), ('Payment Wallet Account', 'Payment Wallet'), ('Smart Home/IoT Account', 'Smart Home/IoT'), ('Social Media Account', 'Social Media'), ('Streaming Media Account', 'Streaming Media'), ('Subscription Account', 'Subscription'), ('Travel Booking Account', 'Travel Booking'), ('Utilities/Telecom Portal Account', 'Utilities or Telecom Portal'), ('Not Listed', 'Not Listed')], default='Email Account', max_length=200),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_critical',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='keep_or_close_instruction',
            field=models.CharField(choices=[('Close Account', 'Close Account'), ('Keep Active', 'Keep Active'), ('Memorialize', 'Memorialize'), ('Other (See Notes)', 'Other (See Notes)')], default='Other (See Notes)', max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('Desktop', 'Desktop'), ('Laptop', 'Laptop'), ('Phone', 'Phone'), ('Smart Watch', 'Smart Watch'), ('Tablet', 'Tablet'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='importantdocument',
            name='document_category',
            field=models.CharField(choices=[('Bank and Cash Accounts', 'Checking, savings, and credit card details.'), ('Business Ownership Documents', 'Operating agreements, partnership and ownership records.'), ('Care Preferences and Providers', 'In-home care, nursing home info, and care instructions.'), ('Charitable Giving and Memberships', 'Charitable plans, affiliations, and organizations.'), ('Cloud and Email Accounts', 'Cloud storage, email accounts, and access credentials.'), ('Dependents and Pet Care', 'Dependent care needs and pet care instructions.'), ('Funeral and Memorial Wishes', 'Funeral, burial, or memorial preferences.'), ('Health Insurance and Benefits', 'Insurance policy details, Medicare/Medicaid info.'), ('Important Personal Documents', 'Birth certificate, marriage certificate, and similar records.'), ('Income and Budgets', 'Income sources, monthly bills, and recurring expenses.'), ('Insurance Policies', 'Life, disability, and long-term care policies.'), ('Investments and Retirement', 'Investment accounts, pensions, and annuities.'), ('Loans and Liabilities', 'Debts, mortgages, and other financial obligations.'), ('Medical Summary', 'Includes allergies, medications, medical history, and specialists.'), ('Notes and Special Instructions', 'Additional notes or specific personal guidance.'), ('Online Accounts and Passwords', 'Online services, financial logins, and subscriptions.'), ('Password Management', 'Password manager info and recovery instructions.'), ('Personal Identification', "Driver's license, passport, and other official IDs."), ('Personal Property and Valuables', 'Inventory of personal valuables.'), ('Property Deeds and Titles', 'Ownership records for homes, vehicles, or land.'), ('Safe Deposit Box Information', 'Location, access instructions, and contents list.'), ('Social Media Accounts', 'Profiles and legacy social media preferences.'), ('Social Security Information', 'Social Security number and benefit details.'), ('Tax and Financial Records', 'Tax returns, property records, and valuation documents.'), ('Not Listed', 'Not Listed')], default='Important Personal Documents', max_length=50),
        ),
    ]
