# Generated by Django 5.2.11 on 2026-03-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_account_slug_contact_slug_device_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyneedstoknowsection',
            name='is_other',
            field=models.BooleanField(default=False),
        ),
    ]
