# Generated by Django 6.0.1 on 2026-02-06 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_delegationgrant_delegate_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegationgrant',
            name='delegate_to',
            field=models.ForeignKey(blank=True, help_text='Contact receiving this delegation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegation_grants', to='dashboard.contact'),
        ),
        migrations.AlterField(
            model_name='delegationgrant',
            name='profile',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='delegation_grants', to='dashboard.profile'),
        ),
    ]
