# Generated by Django 6.0.1 on 2026-01-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_emergencynote_person_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencynote',
            name='person_contact',
            field=models.CharField(choices=[('Spouse', 'Spouse'), ('Daughter', 'Daughter'), ('Daughter-in-law', 'Daughter-in-law'), ('Son', 'Son'), ('Son-in-Law', 'Son-in-Law'), ('Brother', 'Brother'), ('Brother-in-law', 'Brother-in-law'), ('Sister', 'Sister'), ('Sister-in-law', 'Sister-in-law'), ('Father', 'Father'), ('Father-in-law', 'Father-in-low'), ('Mother', 'Mother'), ('Mother-in-law', 'Mother-in-law'), ('Cousin', 'Cousin'), ('Other', 'Other')], max_length=20),
        ),
    ]
