# Generated by Django 5.2.11 on 2026-03-11 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_familyneedstoknowsection_is_other'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relevancereview',
            name='matters',
        ),
    ]
