# Generated by Django 6.0.1 on 2026-01-15 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_emergencynote_person_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencynote',
            name='contact',
        ),
    ]
