# Generated by Django 6.0.1 on 2026-02-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_delegationgrant_delegate_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalestatedocument',
            name='estate_document',
            field=models.CharField(choices=[('Healthcare Documents', [('Advance Directive / Living Will', 'Advance Directive / Living Will — States your wishes for end-of-life or critical medical care.'), ('Durable Power of Attorney for Healthcare', 'Durable Power of Attorney for Healthcare — Authorizes someone to make medical decisions if you cannot.'), ('Living Will / Advance Directive', 'Living Will / Advance Directive — States your wishes for end-of-life or critical medical care.'), ('HIPAA Authorizations', 'HIPAA Authorizations — Allows named individuals to access your medical information.'), ('Organ Donation Preferences', 'Organ Donation Preferences — Documents or forms stating your organ donation wishes.')]), ('Financial and Legal Documents', [('Durable Power of Attorney for Financial Matters', 'Durable Power of Attorney for Financial Matters — Authorizes someone to manage finances if you are incapacitated.'), ('Beneficiary Designations', 'Beneficiary Designations — Forms for life insurance, retirement accounts, etc., naming who receives benefits.'), ('Guardianship Designations', 'Guardianship Designations — Documents naming guardians for minor children or dependents.'), ('Trust Documents', 'Trust Documents — Revocable or irrevocable trust agreements holding and distributing property.')]), ('Estate Administration and Final Instructions', [('Executor / Personal Representative Info', 'Executor / Personal Representative Info — Information about the person(s) designated to administer your estate.'), ('Letter of Instruction', 'Letter of Instruction — Provides guidance for heirs, location of assets, and personal wishes.'), ('Will and Codicils', 'Will and Codicils — Last Will and Testament and any amendments (codicils).')])], default='important_personal_documents', max_length=200, unique=True),
        ),
    ]
