# Generated by Django 5.2.11 on 2026-04-02 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_relevancereview_matters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyneedstoknowsection',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='family_relations', to='dashboard.contact'),
        ),
        migrations.AlterField(
            model_name='funeralplan',
            name='is_veteran',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='importantdocument',
            name='document_category',
            field=models.CharField(choices=[('Bank and Cash Accounts', 'Checking, savings, and credit card details.'), ('Business Ownership Documents', 'Operating agreements, partnership and ownership records.'), ('Care Preferences and Providers', 'In-home care, nursing home info, and care instructions.'), ('Charitable Giving and Memberships', 'Charitable plans, affiliations, and organizations.'), ('Cloud and Email Accounts', 'Cloud storage, email accounts, and access credentials.'), ('Dependents and Pet Care', 'Dependent care needs and pet care instructions.'), ('Funeral and Memorial Wishes', 'Funeral, burial, or memorial preferences.'), ('Health Insurance and Benefits', 'Insurance policy details, Medicare/Medicaid info.'), ('Important Personal Documents', 'Birth certificate, marriage certificate, and similar records.'), ('Income and Budgets', 'Income sources, monthly bills, and recurring expenses.'), ('Insurance Policies', 'Life, disability, and long-term care policies.'), ('Investments and Retirement', 'Investment accounts, pensions, and annuities.'), ('Loans and Liabilities', 'Debts, mortgages, and other financial obligations.'), ('Medical Summary', 'Includes allergies, medications, medical history, and specialists.'), ('Notes and Special Instructions', 'Additional notes or specific personal guidance.'), ('Online Accounts and Passwords', 'Online services, financial logins, and subscriptions.'), ('Password Management', 'Password manager info and recovery instructions.'), ('Personal Identification', "Driver's license, passport, and other official IDs."), ('Personal Property and Valuables', 'Inventory of personal valuables.'), ('Pet License/Records', 'Pet License/Records'), ('Property Deeds and Titles', 'Ownership records for homes, vehicles, or land.'), ('Safe Deposit Box Information', 'Location, access instructions, and contents list.'), ('Social Media Accounts', 'Profiles and legacy social media preferences.'), ('Social Security Information', 'Social Security number and benefit details.'), ('Tax and Financial Records', 'Tax returns, property records, and valuation documents.'), ('Not Listed', 'Not Listed')], max_length=50),
        ),
    ]
