# Generated by Django 6.0.1 on 2026-01-15 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_emergencynote_person_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencynote',
            name='person_contact',
        ),
        migrations.AddField(
            model_name='emergencynote',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_notes', to='dashboard.contact'),
        ),
    ]
