# Generated by Django 5.2.11 on 2026-04-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_familyneedstoknowsection_relation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relevancereview',
            name='last_notified',
            field=models.DateField(blank=True, help_text='Date the reviewer was last emailed a reminder for this review.', null=True),
        ),
    ]
