# Generated by Django 6.0.1 on 2026-02-06 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_digitalestatedocument_estate_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalestatedocument',
            name='title',
        ),
    ]
