# Generated by Django 6.0.1 on 2026-02-06 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_digitalestatedocument_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importantdocument',
            options={'ordering': ['document_category']},
        ),
        migrations.RemoveField(
            model_name='importantdocument',
            name='title',
        ),
    ]
