# Generated by Django 6.0.1 on 2026-01-16 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_emergencynote_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencynote',
            old_name='title',
            new_name='name',
        ),
    ]
