# Generated by Django 6.0.1 on 2026-02-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_importantdocument_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalestatedocument',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='importantdocument',
            name='contact',
        ),
        migrations.AlterField(
            model_name='delegationgrant',
            name='delegation_category',
            field=models.CharField(choices=[('MEDICAL_TREATMENT_DECISIONS', 'Healthcare Decision-Making'), ('FINANCIAL_AUTHORITY', 'Financial Authority'), ('ESTATE_AND_PROPERTY_OVERSIGHT', 'Estate and Property Oversight'), ('PERSONAL_AND_FAMILY_AFFAIRS', 'Personal and Family Affairs')], default='MEDICAL_TREATMENT_DECISIONS', max_length=200),
        ),
        migrations.AlterField(
            model_name='importantdocument',
            name='document_category',
            field=models.CharField(choices=[('Allergies and Sensitivities', 'Summary of known allergies and sensitivities.'), ('Assisted Living or Nursing Home Info', 'Information about facilities, contracts, and preferences.'), ('Budget and Recurring Bills', 'List of monthly bills, due dates, and payment methods.'), ('Business Ownership Documents', 'Ownership records, operating agreements, and related business documents.'), ('Care Preferences at Home', 'Preferences for in-home care, routines, and services.'), ('Charitable Giving Plans', 'Information on current and planned charitable giving.'), ('Cloud Storage Accounts', 'Logins and notes for cloud storage services.'), ('Credit Card Accounts', 'List of credit card accounts and issuers.'), ('Current Medications', 'List of current prescriptions and dosages.'), ('Debts and Liabilities', 'List of outstanding debts, including creditors and terms.'), ('Dependents and Care Needs', 'Information on dependents and their specific care needs.'), ('Digital Subscriptions and Services', 'Online services and subscriptions with access details.'), ('Disability Insurance Policies', 'Policies providing income in case of disability.'), ('Email Accounts', 'Addresses and access details for email accounts.'), ('Funeral and Burial Wishes', 'Preferences for funeral, burial, or cremation.'), ('Health Insurance Policies', 'Policies providing medical coverage.'), ('Important Personal Documents', 'Birth certificate, marriage certificate, etc.'), ('In-Home Care Providers', 'Contact information for in-home care professionals.'), ('Income Sources', 'Employment, pensions, annuities, and other income.'), ('Insurance Policies', 'Life, disability, and other policies relevant to your estate and survivors.'), ('Investment Accounts', 'Brokerage and other investment account information.'), ('Life Insurance Policies', 'Policies paying a benefit upon death.'), ('Loans and Mortgages', 'Details of personal loans and mortgages.'), ('Long-Term Care Insurance', 'Policies covering long-term care needs.'), ('Medical History', 'Summary of past diagnoses, surgeries, and major medical events.'), ('Medical Specialists', 'Contact information for medical specialists.'), ('Medicare / Medicaid Information', 'Coverage details and identification numbers.'), ('Membership and Affiliations', 'Clubs, organizations, and professional memberships.'), ('Memorial Instructions', 'Preferences for memorial services and gatherings.'), ('Notes and Special Instructions', 'Additional notes and instructions not covered elsewhere.'), ('Online Accounts and Passwords', 'List of online services and passwords.'), ('Online Banking and Finance Logins', 'Credentials and notes for online financial accounts.'), ('Password Manager Information', 'Access information for password manager accounts.'), ('Pensions and Annuities', 'Information on pension plans and annuity contracts.'), ('Personal Identification', "Driver's license, passport, and other ID."), ('Personal Property and Valuables', 'Inventory of important personal items and valuables.'), ('Pet Care and Ownership', 'Information and instructions regarding pets.'), ('Primary Bank Accounts', 'Main checking and savings account details.'), ('Primary Physician Information', 'Contact details for primary care physician.'), ('Property Deeds and Titles', 'Deeds, titles, and related ownership documents for real estate and vehicles.'), ('Real Estate Documents', 'Deeds, surveys, and related property records.'), ('Retirement Accounts', '401(k), IRA, and other retirement account details.'), ('Safe Deposit Box Information', 'Location, access, and contents of safe deposit boxes.'), ('Social Media Accounts', 'Accounts and preferences for social media platforms.'), ('Social Security Information', 'Social Security number and benefit information.'), ('Tax Returns and Records', 'Recent tax returns and related records.'), ('Vehicle Titles and Registration', 'Vehicle title and registration documents.')], default='Important Personal Documents', max_length=50),
        ),
    ]
