# Generated by Django 6.0.1 on 2026-02-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_digitalestatedocument_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegationgrant',
            name='delegation_category',
            field=models.CharField(choices=[('ESTATE_AND_PROPERTY_OVERSIGHT', 'Estate and Property Oversight'), ('FAMILY_AFFAIRS', 'Family Affairs'), ('FINANCIAL_AUTHORITY', 'Financial Authority'), ('MEDICAL_TREATMENT_DECISIONS', 'Healthcare Decision-Making'), ('PERSONAL_ITEMS', 'Personal Items')], default='MEDICAL_TREATMENT_DECISIONS', max_length=200),
        ),
        migrations.AlterField(
            model_name='importantdocument',
            name='document_category',
            field=models.CharField(choices=[('Personal Identification', 'Driver’s license, passport, and other official IDs.'), ('Important Personal Documents', 'Birth certificate, marriage certificate, and similar records.'), ('Social Security Information', 'Social Security number and benefit details.'), ('Property Deeds and Titles', 'Ownership records for homes, vehicles, or land.'), ('Safe Deposit Box Information', 'Location, access instructions, and contents list.'), ('Medical Summary', 'Includes allergies, medications, medical history, and specialists.'), ('Care Preferences and Providers', 'In-home care, nursing home info, and care instructions.'), ('Health Insurance and Benefits', 'Insurance policy details, Medicare/Medicaid info.'), ('Dependents and Pet Care', 'Dependent care needs and pet care instructions.'), ('Funeral and Memorial Wishes', 'Funeral, burial, or memorial preferences.'), ('Bank and Cash Accounts', 'Checking, savings, and credit card details.'), ('Loans and Liabilities', 'Debts, mortgages, and other financial obligations.'), ('Investments and Retirement', 'Investment accounts, pensions, and annuities.'), ('Income and Budgets', 'Income sources, monthly bills, and recurring expenses.'), ('Insurance Policies', 'Life, disability, and long-term care policies.'), ('Tax and Financial Records', 'Tax returns, property records, and valuation documents.'), ('Business Ownership Documents', 'Operating agreements, partnership and ownership records.'), ('Charitable Giving and Memberships', 'Charitable plans, affiliations, and organizations.'), ('Online Accounts and Passwords', 'Online services, financial logins, and subscriptions.'), ('Cloud and Email Accounts', 'Cloud storage, email accounts, and access credentials.'), ('Password Management', 'Password manager info and recovery instructions.'), ('Social Media Accounts', 'Profiles and legacy social media preferences.'), ('Personal Property and Valuables', 'Inventory of personal valuables.'), ('Notes and Special Instructions', 'Additional notes or specific personal guidance.')], default='Important Personal Documents', max_length=50),
        ),
    ]
