# Generated by Django 6.0.1 on 2026-01-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_rename_title_emergencynote_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcategory',
            name='name',
            field=models.CharField(choices=[('email', 'Email Account'), ('social_media', 'Social Media Account'), ('cloud_storage', 'Cloud Storage Account'), ('streaming_media', 'Streaming Media Account'), ('ecommerce_marketplace', 'Ecommerce Marketplace Account'), ('online_banking', 'Online Banking Account'), ('neobank_digital_bank', 'Neobank/Digital Bank Account'), ('brokerage_investment', 'Brokerage/Investment Account'), ('cryptocurrency_exchange', 'Cryptocurrency Exchange Account'), ('payment_wallet', 'Payment Wallet Account'), ('payment_processor', 'Payment Processor Account'), ('productivity_collaboration', 'Productivity/Collaboration Account'), ('developer_platform', 'Developer Platform Account'), ('app_store', 'App Store Account'), ('gaming_platform', 'Gaming Platform Account'), ('forum_community', 'Forum/Community Account'), ('education_elearning', 'Education/Elearning Account'), ('subscription_saas', 'Subscription/SaaS Account'), ('government_portal', 'Government Portal Account'), ('utilities_telecom_portal', 'Utilities/Telecom Portal Account'), ('health_portal', 'Health Portal Account'), ('smart_home_iot', 'Smart Home/IoT Account'), ('travel_booking', 'Travel Booking Account'), ('ride_hailing_delivery', 'Ride-Hailing/Delivery Account'), ('password_manager', 'Password Manager Account')], max_length=100),
        ),
    ]
