# Generated by Django 6.0.1 on 2026-02-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_delegationgrant_delegation_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_category',
            field=models.CharField(choices=[('Email Account', 'Email Account'), ('Social Media Account', 'Social Media Account'), ('Cloud Storage Account', 'Cloud Storage Account'), ('Streaming Media Account', 'Streaming Media Account'), ('Ecommerce Marketplace Account', 'Ecommerce Marketplace Account'), ('Online Banking Account', 'Online Banking Account'), ('Neobank/Digital Bank Account', 'Neobank/Digital Bank Account'), ('Brokerage/Investment Account', 'Brokerage/Investment Account'), ('Cryptocurrency Exchange Account', 'Cryptocurrency Exchange Account'), ('Payment Wallet Account', 'Payment Wallet Account'), ('Payment Processor Account', 'Payment Processor Account'), ('App Store Account', 'App Store Account'), ('Gaming Platform Account', 'Gaming Platform Account'), ('Forum/Community Account', 'Forum/Community Account'), ('Education/Elearning Account', 'Education/Elearning Account'), ('Subscription Account', 'Subscription Account'), ('Government Portal Account', 'Government Portal Account'), ('Utilities/Telecom Portal Account', 'Utilities/Telecom Portal Account'), ('Health Portal Account', 'Health Portal Account'), ('Smart Home/IoT Account', 'Smart Home/IoT Account'), ('Travel Booking Account', 'Travel Booking Account'), ('Password Manager Account', 'Password Manager Account'), ('Not Listed', 'Not Listed')], default='email', max_length=200),
        ),
        migrations.AlterField(
            model_name='account',
            name='keep_or_close_instruction',
            field=models.CharField(choices=[('Keep Active', 'Keep Active'), ('Close Account', 'Close Account'), ('Memorialize', 'Memorialize'), ('Other (See Notes)', 'Other (See Notes)')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='carerelationship',
            name='portal_role',
            field=models.CharField(blank=True, choices=[('View Only', 'View Only'), ('Editor', 'Editor'), ('Administrator', 'Administrator')], default='view-only', max_length=20),
        ),
        migrations.AlterField(
            model_name='carerelationship',
            name='relationship_type',
            field=models.CharField(choices=[('Caregiver', 'Caregiver'), ('Healthcare-proxy', 'Healthcare Proxy'), ('Power-of-attorney', 'Power of Attorney'), ('Trustee', 'Trustee'), ('Other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='delegationgrant',
            name='delegation_category',
            field=models.CharField(choices=[('Estate and Property Oversight', 'Estate and Property Oversight'), ('Family Affairs', 'Family Affairs'), ('Financial Authority', 'Financial Authority'), ('Healthcare Decision-Making', 'Healthcare Decision-Making'), ('Personal Items', 'Personal Items')], default='MEDICAL_TREATMENT_DECISIONS', max_length=200),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('Phone', 'Phone'), ('Tablet', 'Tablet'), ('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Smart Watch', 'Smart Watch'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='recoveryrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Denied', 'Denied'), ('Cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
