# Generated by Django 4.2.9 on 2026-01-16 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_accountcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcategory',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='device',
            name='unlock_method_description',
            field=models.CharField(blank=True, help_text='How to unlock (without revealing actual password)', max_length=200),
        ),
    ]
