# Generated by Django 5.2.11 on 2026-04-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_duplicate_important_doc_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalestatedocument',
            name='name_or_title',
            field=models.CharField(blank=True, help_text='Specific name of Document — leave blank to use the category name', max_length=100),
        ),
        migrations.AlterField(
            model_name='importantdocument',
            name='name_or_title',
            field=models.CharField(blank=True, help_text='Specific name of Document — leave blank to use the category name', max_length=100),
        ),
    ]
