# Generated by Django 6.0.1 on 2026-02-09 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_digitalestatedocument_estate_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-is_critical', 'account_name_or_provider']},
        ),
        migrations.RenameField(
            model_name='account',
            old_name='account_name',
            new_name='account_name_or_provider',
        ),
        migrations.RemoveField(
            model_name='account',
            name='provider',
        ),
    ]
