# Generated by Django 6.0.1 on 2026-02-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_account_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='digitalestatedocument',
            options={'ordering': ['-name_or_title', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='digitalestatedocument',
            name='is_active',
        ),
        migrations.AddField(
            model_name='digitalestatedocument',
            name='file',
            field=models.FileField(blank=True, help_text='Upload digital copy', null=True, upload_to='documents/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='digitalestatedocument',
            name='name_or_title',
            field=models.CharField(default=1, help_text='Specific name of Document', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importantdocument',
            name='name_or_title',
            field=models.CharField(default=1, help_text='Specific name of Document', max_length=100),
            preserve_default=False,
        ),
    ]
