# Generated by Django 5.2.11 on 2026-04-27 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_document_access_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentaccesslog',
            name='estate_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='dashboard.digitalestatedocument'),
        ),
    ]
