# Generated by Django 6.0.1 on 2026-02-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_digitalestatedocument_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalestatedocument',
            name='file',
        ),
        migrations.AddField(
            model_name='digitalestatedocument',
            name='estate_file',
            field=models.FileField(blank=True, help_text='Upload digital copy', null=True, upload_to='documents/%Y/%m/'),
        ),
    ]
