# Generated by Django 5.2.11 on 2026-04-27 19:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_estate_doc_access_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['profile'], name='primary_con_profile_6b1cd0_idx'),
        ),
    ]
