# Generated by Django 6.0.1 on 2026-02-09 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_remove_digitalestatedocument_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importantdocument',
            old_name='file',
            new_name='important_file',
        ),
    ]
