# Generated by Django 6.0.1 on 2026-02-19 17:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text='Recipient email address.', max_length=254)),
                ('first_name', models.CharField(blank=True, default='', help_text='Optional first name provided by the requester.', max_length=80)),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the checklist email was successfully sent.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the requester.', null=True)),
                ('converted', models.BooleanField(default=False, help_text='Did this lead eventually create an account?')),
                ('notes', models.TextField(blank=True, default='', help_text='Internal admin notes about this lead.')),
            ],
            options={
                'verbose_name': 'Checklist Email Log',
                'verbose_name_plural': 'Checklist Email Logs',
                'db_table': 'checklist_email_log',
                'ordering': ['-sent_at'],
            },
        ),
    ]
