# Generated by Django 6.0.1 on 2026-02-16 21:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0003_remove_recoveryrequest_recovery_re_status_41ec4e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_first_name', models.CharField(blank=True, max_length=100)),
                ('requester_last_name', models.CharField(blank=True, max_length=100)),
                ('requester_email', models.EmailField(blank=True, max_length=254)),
                ('requester_phone', models.CharField(blank=True, max_length=20)),
                ('requester_relationship', models.CharField(blank=True, help_text='Relationship to account owner', max_length=50)),
                ('verification_token', models.CharField(blank=True, editable=False, help_text="Token sent to requester's email for verification", max_length=100, unique=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_attempts', models.PositiveSmallIntegerField(default=0)),
                ('reason', models.CharField(choices=[('Death', 'Account owner is deceased'), ('Incapacitation', 'Account owner is incapacitated'), ('Other', 'Other circumstance')], default='Death', max_length=20)),
                ('target_description', models.CharField(help_text='Description of what needs to be recovered', max_length=500)),
                ('death_certificate', models.FileField(blank=True, help_text='Death certificate or medical documentation', null=True, upload_to='recovery_requests/certificates/%Y/%m/')),
                ('proof_of_relationship', models.FileField(blank=True, help_text='Proof of relationship (e.g., marriage certificate, birth certificate)', null=True, upload_to='recovery_requests/proof/%Y/%m/')),
                ('legal_authorization', models.FileField(blank=True, help_text='Power of attorney, executor documentation, court order, etc.', null=True, upload_to='recovery_requests/legal/%Y/%m/')),
                ('additional_notes', models.TextField(blank=True, help_text='Additional information supporting the request')),
                ('status', models.CharField(choices=[('Pending Verification', 'Pending Verification'), ('Verified', 'Verified'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Denied', 'Denied'), ('Cancelled', 'Cancelled')], default='Pending Verification', max_length=25)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('provider_ticket_number', models.CharField(blank=True, help_text='External service provider ticket/case number', max_length=100)),
                ('steps_taken', models.TextField(blank=True, help_text='Actions taken to process this request')),
                ('outcome_notes', models.TextField(blank=True, help_text='Final outcome and resolution details')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(editable=False, help_text='Profile of the deceased/incapacitated user', on_delete=django.db.models.deletion.CASCADE, related_name='recovery_requests', to='dashboard.profile')),
                ('requested_by_user', models.ForeignKey(blank=True, help_text='Authenticated user making the request (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_requests_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_recovery_requests', to=settings.AUTH_USER_MODEL)),
                ('target_account', models.ForeignKey(blank=True, help_text='Specific account to recover (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_requests', to='dashboard.account')),
            ],
            options={
                'db_table': 'recovery_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='recovery_re_status_41ec4e_idx'), models.Index(fields=['verification_token'], name='recovery_re_verific_428f8f_idx'), models.Index(fields=['requester_email'], name='recovery_re_request_a62e7e_idx')],
            },
        ),
    ]
