# Generated by Django 5.2.11 on 2026-03-20 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_relevancereview_matters'),
        ('recovery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiry date.  Leave blank for indefinite access.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to revoke access without deleting the record.')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about why this grant was created.')),
                ('granted_by', models.ForeignKey(help_text='Admin who created this grant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grants_issued', to=settings.AUTH_USER_MODEL)),
                ('granted_to', models.ForeignKey(help_text='User who receives read-only access to the profile.', on_delete=django.db.models.deletion.CASCADE, related_name='profile_access_grants', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(help_text='The estate profile being shared.', on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='dashboard.profile')),
                ('recovery_request', models.ForeignKey(blank=True, help_text='The recovery request that justified this grant (audit trail).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_grants', to='recovery.recoveryrequest')),
            ],
            options={
                'db_table': 'profile_access_grants',
                'ordering': ['-granted_at'],
                'indexes': [models.Index(fields=['granted_to', 'is_active'], name='profile_acc_granted_a07096_idx')],
                'unique_together': {('profile', 'granted_to')},
            },
        ),
    ]
