# Generated by Django 5.2.11 on 2026-04-08 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_add_review_last_notified'),
        ('recovery', '0002_profile_access_grant'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileaccessgrant',
            name='expiry_notified',
            field=models.BooleanField(default=False, help_text='True once the grantee has been emailed about upcoming expiry. Reset to False if expires_at is extended so the reminder fires again.'),
        ),
        migrations.AlterField(
            model_name='profileaccessgrant',
            name='profile',
            field=models.ForeignKey(help_text='The estate profile being shared. Protected: revoke all grants before deleting the profile.', on_delete=django.db.models.deletion.PROTECT, related_name='access_grants', to='dashboard.profile'),
        ),
    ]
