# Generated by Django 5.2.11 on 2026-04-09 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0003_protect_profile_grant_and_expiry_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileaccessgrant',
            name='notes',
        ),
    ]
