# Generated by Django 5.2.11 on 2026-03-06 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0003_account_slug_contact_slug_device_slug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('account', 'Digital Account'), ('device', 'Device'), ('other', 'Other / Standalone')], default='other', max_length=20)),
                ('label', models.CharField(help_text="A descriptive label, e.g. 'Gmail master password' or 'iPhone PIN'.", max_length=200)),
                ('username_or_email', models.CharField(blank=True, help_text='The login identifier (username or email). Not encrypted.', max_length=254)),
                ('notes', models.TextField(blank=True, help_text='Additional context — recovery codes, security questions, etc.')),
                ('encrypted_password', models.TextField(help_text='Fernet-encrypted password token. Never store plaintext here.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed', models.DateTimeField(blank=True, help_text='Timestamp of the most recent decryption / reveal.', null=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('linked_account', models.ForeignKey(blank=True, help_text='The Account this credential belongs to (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vault_entries', to='dashboard.account')),
                ('linked_device', models.ForeignKey(blank=True, help_text='The Device this PIN / password belongs to (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vault_entries', to='dashboard.device')),
                ('profile', models.ForeignKey(help_text='Owner profile.', on_delete=django.db.models.deletion.CASCADE, related_name='vault_entries', to='dashboard.profile')),
            ],
            options={
                'verbose_name': 'Vault Entry',
                'verbose_name_plural': 'Vault Entries',
                'db_table': 'vault_entries',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='VaultAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('accessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='infrapps.vaultentry')),
            ],
            options={
                'db_table': 'vault_access_logs',
                'ordering': ['-accessed_at'],
            },
        ),
    ]
