# Generated by Django 5.2.11 on 2026-04-01 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrapps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaultentry',
            name='entry_type',
        ),
    ]
