# Generated by Django 5.2.11 on 2026-04-06 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrapps', '0002_remove_entry_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaultentry',
            name='label',
        ),
    ]
