# Generated by Django 5.2.11 on 2026-04-09 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrapps', '0003_remove_vaultentry_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaultentry',
            name='notes',
        ),
    ]
