# Generated by Django 5.2.11 on 2026-03-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='addon_active',
            field=models.BooleanField(default=False, help_text='User has an active add-on subscription'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='addon_expires',
            field=models.DateTimeField(blank=True, help_text='When the add-on subscription expires (1 year from purchase, renewable)', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='addon_payment_date',
            field=models.DateTimeField(blank=True, help_text='Date the add-on was purchased', null=True),
        ),
    ]
