# Generated by Django 5.2.11 on 2026-03-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_addon_active_customuser_addon_expires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='User is in demo/free-trial mode — changes are not persisted'),
        ),
    ]
