# Generated by Django 5.2.11 on 2026-03-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', help_text='Stripe customer ID (cus_...)', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, default='', help_text='Stripe subscription ID (sub_...)', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_cancel_at_period_end',
            field=models.BooleanField(default=False, help_text='Subscription is set to cancel at end of current billing period'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_current_period_end',
            field=models.DateTimeField(blank=True, help_text='End of current Stripe billing period', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_interval',
            field=models.CharField(blank=True, choices=[('', 'Not Set'), ('monthly', 'Monthly'), ('annual', 'Annual')], default='', help_text='Billing interval: monthly or annual', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_status',
            field=models.CharField(blank=True, choices=[('', 'Not Set'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired'), ('trialing', 'Trialing'), ('unpaid', 'Unpaid')], default='', help_text='Current Stripe subscription status', max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='essentials_expires',
            field=models.DateTimeField(blank=True, help_text='[Legacy one-time] When Essentials edit access expires', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='has_paid',
            field=models.BooleanField(default=False, help_text='User has completed at least one payment (used for view-only access after cancellation)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='legacy_granted_date',
            field=models.DateTimeField(blank=True, help_text='[Legacy one-time] When lifetime legacy access was granted', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='payment_date',
            field=models.DateTimeField(blank=True, help_text='Date of most recent payment or subscription start', null=True),
        ),
    ]
