# Generated by Django 5.2.11 on 2026-03-24 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_demo',
        ),
    ]
