# Generated by Django 5.2.11 on 2026-04-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_is_demo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='essentials_expires',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='legacy_granted_date',
        ),
    ]
