# Generated by Django 5.2.11 on 2026-04-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_one_time_payment_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='addon_active',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='addon_expires',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='addon_payment_date',
        ),
    ]
