# Generated by Django 5.2.11 on 2026-04-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_addon_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of when the user accepted the Terms and Conditions, Privacy Policy, and Cookie Policy.', null=True),
        ),
    ]
